import { tripcartColors } from '@tripcart/design-tokens'

export const COLORS = {
  primary50: tripcartColors.primary[50],
  primary100: tripcartColors.primary[100],
  primary300: tripcartColors.primary[300],
  primary500: tripcartColors.primary[500],
  primary700: tripcartColors.primary[700],
  primary900: tripcartColors.primary[900],
  plum50: tripcartColors.plum[50],
  plum100: tripcartColors.plum[100],
  plum300: tripcartColors.plum[300],
  plum500: tripcartColors.plum[500],
  plum700: tripcartColors.plum[700],
  coral50: tripcartColors.coral[50],
  coral500: tripcartColors.coral[500],
  coral900: tripcartColors.coral[900],
  gold50: tripcartColors.gold[50],
  gold300: tripcartColors.gold[300],
  gold500: tripcartColors.gold[500],
  gold900: tripcartColors.gold[900],
  neutral0: tripcartColors.neutral[0],
  neutral50: tripcartColors.neutral[50],
  neutral100: tripcartColors.neutral[100],
  neutral300: tripcartColors.neutral[300],
  neutral500: tripcartColors.neutral[500],
  neutral700: tripcartColors.neutral[700],
  neutral900: tripcartColors.neutral[900],
  successLight: tripcartColors.success.light,
  success: tripcartColors.success.DEFAULT,
  successDark: tripcartColors.success.dark,
  infoLight: tripcartColors.info.light,
  infoDark: tripcartColors.info.dark,
} as const

export const HERO_IMAGE =
  'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80'

export const PLAN_IMAGES = [
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=1200&q=80',
] as const

export const PLACE_CARDS = [
  {
    id: 'gamcheon',
    name: '감천문화마을',
    region: '부산 사하구',
    category: '관광지',
    tags: ['관광지', '포토존'],
    status: '영업중',
    statusTone: 'open',
    dwellMinutes: 90,
    travelMinutes: 28,
    qualityScore: 92,
    saved: true,
    image: 'https://images.unsplash.com/photo-1549693578-d683be217e58?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'gomjangeo',
    name: '해운대곰장어',
    region: '부산 해운대구 중동',
    category: '식당',
    tags: ['맛집', '해물'],
    status: 'BT 14:30 전 도착 권장',
    statusTone: 'risk',
    dwellMinutes: 60,
    travelMinutes: 36,
    qualityScore: 95,
    saved: false,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'gwangalli',
    name: '광안리해변',
    region: '부산 수영구',
    category: '관광지',
    tags: ['뷰맛집', '야경'],
    status: '24시간 산책 가능',
    statusTone: 'open',
    dwellMinutes: 90,
    travelMinutes: 22,
    qualityScore: 88,
    saved: true,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'jagalchi',
    name: '자갈치시장',
    region: '부산 중구',
    category: '식당',
    tags: ['맛집', '시장'],
    status: '라스트오더 확인 필요',
    statusTone: 'warning',
    dwellMinutes: 60,
    travelMinutes: 18,
    qualityScore: 83,
    saved: false,
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'haeundae',
    name: '해운대해수욕장',
    region: '부산 해운대구',
    category: '관광지',
    tags: ['해변', '산책'],
    status: '주차 혼잡 예상',
    statusTone: 'warning',
    dwellMinutes: 80,
    travelMinutes: 14,
    qualityScore: 90,
    saved: false,
    image: 'https://images.unsplash.com/photo-1520201163981-8cc95007dd2e?auto=format&fit=crop&w=900&q=80',
  },
] as const

export const BROWSE_FILTERS = ['전체', '관광지', '식당', '카페'] as const

export const FEATURED_PLANS = [
  {
    title: '부산 주말 드라이브',
    date: '2026. 4. 14 - 2026. 4. 16',
    badge: '초안',
    image: PLAN_IMAGES[0],
  },
  {
    title: '설악산 단풍 여행',
    date: '2026. 10. 25 - 2026. 10. 27',
    badge: '예정',
    image: PLAN_IMAGES[1],
  },
  {
    title: '서울 시티 투어',
    date: '2026. 12. 20 - 2026. 12. 22',
    badge: '예정',
    image: PLAN_IMAGES[2],
  },
] as const

export const TIMELINE_ITEMS = [
  { time: '오전 10:00', title: '감천문화마을' },
  { time: '오후 1:30', title: '해운대해수욕장' },
  { time: '오후 3:45', title: '모모스커피 전포' },
  { time: '오후 5:20', title: '모모스커피안' },
] as const

export const PLAN_SUMMARY = {
  id: 'busan-day-1',
  title: '부산 당일치기 실행 플랜',
  date: '2026. 5. 2 토요일',
  startTime: '오전 9:00',
  region: '부산',
  transport: '자동차',
  status: '최적화 완료',
  totalTime: '8시간 20분',
  totalDistance: '47.3km',
  warning: '해운대곰장어는 브레이크타임 전에 도착해야 합니다.',
  image: PLAN_IMAGES[0],
} as const

export const PLAN_STOPS = [
  {
    id: 'stop-gamcheon',
    order: 1,
    time: '오전 10:00',
    name: '감천문화마을',
    category: '관광지',
    status: '영업중',
    statusTone: 'open',
    dwell: '90분 체류',
    travelFromPrev: '부산역에서 28분',
    note: '언덕 구간이 있어 여유 있게 시작합니다.',
    image: PLACE_CARDS[0].image,
  },
  {
    id: 'stop-gomjangeo',
    order: 2,
    time: '오전 11:55',
    name: '해운대곰장어',
    category: '식당',
    status: 'BT 전 도착',
    statusTone: 'risk',
    dwell: '60분 체류',
    travelFromPrev: '이전 장소에서 36분',
    note: '14:30 브레이크타임 전에 식사를 마칩니다.',
    image: PLACE_CARDS[1].image,
  },
  {
    id: 'stop-haeundae',
    order: 3,
    time: '오후 1:25',
    name: '해운대해수욕장',
    category: '관광지',
    status: '주차 주의',
    statusTone: 'warning',
    dwell: '80분 체류',
    travelFromPrev: '이전 장소에서 14분',
    note: '해변 산책 후 다음 카페까지 짧게 이동합니다.',
    image: PLACE_CARDS[4].image,
  },
  {
    id: 'stop-gwangalli',
    order: 4,
    time: '오후 4:20',
    name: '광안리해변',
    category: '관광지',
    status: '야경 추천',
    statusTone: 'open',
    dwell: '90분 체류',
    travelFromPrev: '이전 장소에서 22분',
    note: '일몰 전 도착해 야경까지 이어집니다.',
    image: PLACE_CARDS[2].image,
  },
] as const
